---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: web-app
    labels:
      app: web-app
  spec:
    type: ClusterIP
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: web-app
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web-app
    labels:
      app: web-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web-app
    template:
      metadata:
        labels:
          app: web-app
      spec:
        containers:
        - name: web-app
          image: registry.dev.svc.cluster.local:5001/web-app:nginx
