FROM node:16-alpine3.11 as build

WORKDIR /app

# install app dependencies
#copies package.json and package-lock.json to Docker environment
COPY --chown=node:node package.json ./

ENV NODE_ENV production
# Installs all node packages
RUN npm install 

COPY --chown=node:node  . ./
# Now build
RUN npm run build --only=production

#Stage 2
#######################################
#pull the official nginx:1.19.0 base image
FROM nginx:1.19.0
#copies React to the container directory
# Set working directory to nginx resources directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=build /app/build .
# Containers run nginx with global directives and daemon off
# ENTRYPOINT ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]